---
- name: Get vLLM service URL
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: vllm
    namespace: "{{ llamastack_ns }}"
  register: vllm_route_info

- name: Set vLLM URL fact
  ansible.builtin.set_fact:
    vllm_url: "http://{{ vllm_route_info.resources[0].spec.host }}/v1"

- name: Display vLLM URL
  ansible.builtin.debug:
    msg: "vLLM URL: {{ vllm_url }}"

- name: Display FMS Orchestrator URL
  ansible.builtin.debug:
    msg: "FMS Orchestrator URL: {{ llamastack_distribution.fms_orchestrator_url }}"

- name: Create LlamaStack Distribution CR with vLLM and Milvus DB
  kubernetes.core.k8s:
    state: present
    definition: |
      apiVersion: llamastack.io/v1alpha1
      kind: LlamaStackDistribution
      metadata:
        name: {{ llamastack_distribution.name }}
        namespace: {{ llamastack_ns }}
      spec:
        replicas: {{ llamastack_distribution.replicas }}
        server:
          containerSpec:
            env:
              - name: INFERENCE_MODEL
                value: {{ llamastack_distribution.inference_model }}
              - name: VLLM_URL
                value: {{ vllm_url }}
              - name: MILVUS_DB_PATH
                value: {{ llamastack_distribution.milvus_db_path }}
              - name: FMS_ORCHESTRATOR_URL
                value: {{ llamastack_distribution.fms_orchestrator_url }}
            name: llama-stack
            port: {{ llamastack_distribution.port }}
          distribution:
            image: {{ llamastack_distribution.image | quote }}

- name: Wait for LlamaStack Distribution to be ready
  kubernetes.core.k8s_info:
    api_version: llamastack.io/v1alpha1
    kind: LlamaStackDistribution
    name: "{{ llamastack_distribution.name }}"
    namespace: "{{ llamastack_ns }}"
  register: distribution_status
  retries: 30
  delay: 20
  until: distribution_status.resources | length > 0

- name: Display LlamaStack Distribution status
  ansible.builtin.debug:
    msg: "LlamaStack Distribution Status:"
  
- name: Display distribution name
  ansible.builtin.debug:
    msg: "- Name: {{ distribution_status.resources[0].metadata.name }}"
  
- name: Display distribution namespace
  ansible.builtin.debug:
    msg: "- Namespace: {{ distribution_status.resources[0].metadata.namespace }}"
  
- name: Display distribution status
  ansible.builtin.debug:
    msg: "- Status: {{ distribution_status.resources[0].status | default('Not available yet') }}"

- name: Create LlamaStack Distribution HTTP route
  kubernetes.core.k8s:
    state: present
    definition: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: {{ llamastack_distribution.name }}-http
        namespace: {{ llamastack_ns }}
        labels:
          app.kubernetes.io/name: {{ llamastack_distribution.name }}
          route-type: http
      spec:
        to:
          kind: Service
          name: {{ llamastack_distribution.name }}-service
          weight: 100
        port:
          targetPort: {{ llamastack_distribution.port }}

- name: Create LlamaStack Distribution HTTPS route
  kubernetes.core.k8s:
    state: present
    definition: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: {{ llamastack_distribution.name }}-https
        namespace: {{ llamastack_ns }}
        labels:
          app.kubernetes.io/name: {{ llamastack_distribution.name }}
          route-type: https
      spec:
        to:
          kind: Service
          name: {{ llamastack_distribution.name }}-service
          weight: 100
        port:
          targetPort: {{ llamastack_distribution.port }}
        tls:
          termination: edge

- name: Get LlamaStack Distribution HTTP route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: "{{ llamastack_distribution.name }}-http"
    namespace: "{{ llamastack_ns }}"
  register: distribution_http_route_info
  retries: 10
  delay: 5
  until: distribution_http_route_info.resources | length > 0

- name: Get LlamaStack Distribution HTTPS route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: "{{ llamastack_distribution.name }}-https"
    namespace: "{{ llamastack_ns }}"
  register: distribution_https_route_info
  retries: 10
  delay: 5
  until: distribution_https_route_info.resources | length > 0

- name: Set distribution HTTP route URL fact
  ansible.builtin.set_fact:
    distribution_http_route_url: "http://{{ distribution_http_route_info.resources[0].spec.host }}"

- name: Set distribution HTTPS route URL fact
  ansible.builtin.set_fact:
    distribution_https_route_url: "https://{{ distribution_https_route_info.resources[0].spec.host }}"

- name: Wait for LlamaStack Distribution service to be ready
  ansible.builtin.pause:
    seconds: 30
  when: distribution_http_route_info.resources | length > 0 and distribution_https_route_info.resources | length > 0

- name: Smoke test - Check LlamaStack Distribution health endpoint (HTTPS)
  ansible.builtin.uri:
    url: "{{ distribution_https_route_url }}/v1/health"
    method: GET
    validate_certs: false
    status_code: 200
    timeout: 30
  register: health_check
  retries: 5
  delay: 10
  until: health_check.status == 200

- name: Display health check success
  ansible.builtin.debug:
    msg: "✅ Health endpoint is responding: {{ health_check.status }}"
  when: health_check is defined and health_check.status is defined

- name: Smoke test - Get available models (HTTPS)
  ansible.builtin.uri:
    url: "{{ distribution_https_route_url }}/v1/models"
    method: GET
    validate_certs: false
    status_code: 200
    timeout: 30
  register: models_check
  retries: 5
  delay: 10
  until: models_check.status == 200

- name: Parse models response
  ansible.builtin.set_fact:
    models_data: "{{ models_check.json }}"
  when: models_check is defined and models_check.json is defined

- name: Display models smoke test success
  ansible.builtin.debug:
    msg: "✅ Models endpoint is responding: {{ models_check.status }}"
  when: models_check is defined and models_check.status is defined

- name: Display available models
  ansible.builtin.debug:
    msg: "🎯 Available Models:"
  when: models_data is defined

- name: Display LLM model
  ansible.builtin.debug:
    msg: "• LLM Model: {{ models_data.data | selectattr('model_type', 'equalto', 'llm') | map(attribute='identifier') | first | default('Not found') }}"
  when: models_data is defined and models_data.data is defined

- name: Display embedding model
  ansible.builtin.debug:
    msg: "• Embedding Model: {{ models_data.data | selectattr('model_type', 'equalto', 'embedding') | map(attribute='identifier') | first | default('Not found') }}"
  when: models_data is defined and models_data.data is defined

- name: Display total models count
  ansible.builtin.debug:
    msg: "• Total Models: {{ models_data.data | length }}"
  when: models_data is defined and models_data.data is defined

- name: Display LlamaStack Distribution completion
  ansible.builtin.debug:
    msg: "✅ LlamaStack Distribution with vLLM and Milvus DB has been deployed successfully!"

- name: Display distribution details
  ansible.builtin.debug:
    msg: "🎯 LlamaStack Distribution Details:"

- name: Display distribution name
  ansible.builtin.debug:
    msg: "• Name: {{ llamastack_distribution.name }}"

- name: Display distribution image
  ansible.builtin.debug:
    msg: "• Image: {{ llamastack_distribution.image }}"

- name: Display inference model
  ansible.builtin.debug:
    msg: "• Inference Model: {{ llamastack_distribution.inference_model }}"

- name: Display vLLM URL
  ansible.builtin.debug:
    msg: "• vLLM URL: {{ vllm_url }}"

- name: Display distribution HTTP route
  ansible.builtin.debug:
    msg: "• HTTP Route: {{ distribution_http_route_url }}"

- name: Display distribution HTTPS route
  ansible.builtin.debug:
    msg: "• HTTPS Route: {{ distribution_https_route_url }}"

- name: Display access information
  ansible.builtin.debug:
    msg: "📋 Access LlamaStack Distribution:"

- name: Display HTTP access
  ansible.builtin.debug:
    msg: "🌐 HTTP Access:"

- name: Display HTTP web interface
  ansible.builtin.debug:
    msg: "• Web Interface: {{ distribution_http_route_url }}"

- name: Display HTTP API documentation
  ansible.builtin.debug:
    msg: "• API Documentation: {{ distribution_http_route_url }}/docs"

- name: Display HTTP models endpoint
  ansible.builtin.debug:
    msg: "• Models Endpoint: {{ distribution_http_route_url }}/v1/models"

- name: Display HTTP chat completions endpoint
  ansible.builtin.debug:
    msg: "• Chat Completions: {{ distribution_http_route_url }}/v1/openai/v1/chat/completions"

- name: Display HTTPS access
  ansible.builtin.debug:
    msg: "🔒 HTTPS Access:"

- name: Display HTTPS web interface
  ansible.builtin.debug:
    msg: "• Web Interface: {{ distribution_https_route_url }}"

- name: Display HTTPS API documentation
  ansible.builtin.debug:
    msg: "• API Documentation: {{ distribution_https_route_url }}/docs"

- name: Display HTTPS models endpoint
  ansible.builtin.debug:
    msg: "• Models Endpoint: {{ distribution_https_route_url }}/v1/models"

- name: Display HTTPS chat completions endpoint
  ansible.builtin.debug:
    msg: "• Chat Completions: {{ distribution_https_route_url }}/v1/openai/v1/chat/completions"

- name: Display monitoring commands
  ansible.builtin.debug:
    msg: "🔍 Monitor the deployment:"

- name: Display kubectl get command
  ansible.builtin.debug:
    msg: "kubectl get llamastackdistribution {{ llamastack_distribution.name }} -n {{ llamastack_ns }}"

- name: Display kubectl describe command
  ansible.builtin.debug:
    msg: "kubectl describe llamastackdistribution {{ llamastack_distribution.name }} -n {{ llamastack_ns }}"

- name: Display pods command
  ansible.builtin.debug:
    msg: "kubectl get pods -n {{ llamastack_ns }} -l app.kubernetes.io/name={{ llamastack_distribution.name }}"
