---
- name: STEP 4 - Deploy LlamaStack Distribution with vLLM and Milvus DB
  hosts: local
  gather_facts: false

  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig }}"
    kubernetes.core.k8s_info:
      kubeconfig: "{{ kubeconfig }}"

  vars_files:
    - ../group_vars/all.yml

  roles:
    - llamastack_distribution
